/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BattleService } from "../battle.service";
import { BattleCreateInput } from "./BattleCreateInput";
import { Battle } from "./Battle";
import { BattleFindManyArgs } from "./BattleFindManyArgs";
import { BattleWhereUniqueInput } from "./BattleWhereUniqueInput";
import { BattleUpdateInput } from "./BattleUpdateInput";
import { AttendanceFindManyArgs } from "../../attendance/base/AttendanceFindManyArgs";
import { Attendance } from "../../attendance/base/Attendance";
import { AttendanceWhereUniqueInput } from "../../attendance/base/AttendanceWhereUniqueInput";

export class BattleControllerBase {
  constructor(protected readonly service: BattleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Battle })
  async createBattle(@common.Body() data: BattleCreateInput): Promise<Battle> {
    return await this.service.createBattle({
      data: data,
      select: {
        battleId: true,
        createdAt: true,
        endTime: true,
        fame: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Battle] })
  @ApiNestedQuery(BattleFindManyArgs)
  async battles(@common.Req() request: Request): Promise<Battle[]> {
    const args = plainToClass(BattleFindManyArgs, request.query);
    return this.service.battles({
      ...args,
      select: {
        battleId: true,
        createdAt: true,
        endTime: true,
        fame: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Battle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async battle(
    @common.Param() params: BattleWhereUniqueInput
  ): Promise<Battle | null> {
    const result = await this.service.battle({
      where: params,
      select: {
        battleId: true,
        createdAt: true,
        endTime: true,
        fame: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Battle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBattle(
    @common.Param() params: BattleWhereUniqueInput,
    @common.Body() data: BattleUpdateInput
  ): Promise<Battle | null> {
    try {
      return await this.service.updateBattle({
        where: params,
        data: data,
        select: {
          battleId: true,
          createdAt: true,
          endTime: true,
          fame: true,
          id: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Battle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBattle(
    @common.Param() params: BattleWhereUniqueInput
  ): Promise<Battle | null> {
    try {
      return await this.service.deleteBattle({
        where: params,
        select: {
          battleId: true,
          createdAt: true,
          endTime: true,
          fame: true,
          id: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/attendances")
  @ApiNestedQuery(AttendanceFindManyArgs)
  async findAttendances(
    @common.Req() request: Request,
    @common.Param() params: BattleWhereUniqueInput
  ): Promise<Attendance[]> {
    const query = plainToClass(AttendanceFindManyArgs, request.query);
    const results = await this.service.findAttendances(params.id, {
      ...query,
      select: {
        attendanceStatus: true,

        battle: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attendances")
  async connectAttendances(
    @common.Param() params: BattleWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        connect: body,
      },
    };
    await this.service.updateBattle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attendances")
  async updateAttendances(
    @common.Param() params: BattleWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        set: body,
      },
    };
    await this.service.updateBattle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attendances")
  async disconnectAttendances(
    @common.Param() params: BattleWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        disconnect: body,
      },
    };
    await this.service.updateBattle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
